### ISSUE TITLE
[01] Fazer uma tela final exibindo a pontuação e a opção de encerrar o formulário.

### ISSUE THREAD

**Issue by RafaelSantosBraz** [mykeoliveira/ESProject#3]
Na tela dos questionários, ao clicar em “próximo” na última questão é exibida uma tela com o número de acertos
--

**Comment by mykeoliveira** [comment]
Solicitação de mudança viável, com complexidade média.
Pode ser implementada em até 1 dia.

**Comment by mykeoliveira** [comment]
Os testes com a ferramenta Selenium passaram e a CR já pode ser fechada
