### ISSUE TITLE
[02] Criar botão de pular pergunta

### ISSUE THREAD

**Issue by RafaelSantosBraz** [mykeoliveira/ESProject#4]
Opção para permitir ao usuário ir para a próxima questão sem precisar preencher qualquer campo

**Comment by WallaceManzano** [comment]
CR viável e com complexidade baixa, podendo ser realizada em 1 dia.

**Comment by WallaceManzano** [comment]
CR foi implementada pela pull request #15 , criando um botão pular para trafegar pular uma questão. A CR foi testada e implantada na branch principal.
