### ISSUE TITLE
[06] Poder refazer o questionário dos estilos cognitivos

### ISSUE THREAD

**Issue by RafaelSantosBraz** [mykeoliveira/ESProject#7]
Essa opção deve ser disponibilizada na página em que o resultado do questionário é apresentado ao usuário

**Comment by rodrigofsouza9** [comment]
É uma solicitação viável, de baixa complexidade, dependendo somente da elaboração da tela em que o resultado é apresentado ao usuário. Tempo estimado de um dia.
