### ISSUE TITLE
[07] Poder refazer o questionário que avalia o conhecimento prévio dos usuários

### ISSUE THREAD

**Issue by RafaelSantosBraz** [mykeoliveira/ESProject#8]
Essa opção deve ser disponibilizada na página em que o resultado do questionário é apresentado ao usuário

**Comment by pedro87azevedo** [comment]
Essa opção deve ser disponibilizada na página em que o resultado do questionário é apresentado ao usuário, tem baixa prioridade e média complexidade.

**Comment by neoluizz** [comment]
**Essa opção deve ser disponibilizada na página em que o resultado do questionário é apresentado ao usuário.**

Por ser uma CR simples, optamos por aprová-la; entretanto, com prioridade _baixa_ devido ao fato de não ser essencial para o funcionamento do sistema.

Tempo necessário para realização da tarefa: 1 dia.

**Comment by neoluizz** [comment]
Concluída
