### ISSUE TITLE
[08] Corrigir o formulário de cadastro de usuários

### ISSUE THREAD

**Issue by RafaelSantosBraz** [mykeoliveira/ESProject#9]
O formulário não deve permitir que mais de um usuário tenham o mesmo login

**Comment by pedro87azevedo** [comment]
**O formulário não deve permitir que mais de um usuário possua o mesmo _login_.**

Como o _login_ pode vir a ser um modo de identificar o usuário, optamos por aprovar a CR.

Com relação a complexidade, optamos por defini-la como _média_, dado que possíveis consultas por usuários poderão ser feitas ser feitas pelo _login_.

 O tempo estimado para a conclusão da tarefa é de 2 dias; esse tempo foi definido já considerando o tempo necessário para testes.

**Comment by neoluizz** [comment]
Concluído
